# Generated by Django 2.1.5 on 2020-06-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boot_Table',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Contact', models.IntegerField(default='')),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
